### ISSUE TITLE
Error when added to the page.

### ISSUE THREAD

**Issue by mastj25** [CloudDesignBox/cdb-promoted-links#1]
I have uploaded the CDBPromotedLinks to Site Assets and the app to the app catalog as instructed.  I am able to see Promoted App on my modern page but I get the following error when I add it to the page.  Any suggestions?

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart).
Original error: ***Failed to load URL '/SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js' for resource 'CloudDesignBoxPromotedLinksWebPartStrings' in component '5b0eac5a-50ba-4e01-8eb4-1767151d07f8' (CloudDesignBoxPromotedLinksWebPart). The file was not found in the server.

***INNERERROR:
***Failed to load URL '/SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js' for resource 'CloudDesignBoxPromotedLinksWebPartStrings' in component '5b0eac5a-50ba-4e01-8eb4-1767151d07f8' (CloudDesignBoxPromotedLinksWebPart). The file was not found in the server.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:308:15646)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:793:37403)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:793:43292)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:793:39735)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:793:11333

**Comment by CloudDesignBox** [comment]
It looks like the folder doesn't exist where it expects it to be.

The files need to be uploaded to the root site collections top level site assets library.
You should be able to browse it by going to https://tenantname.sharepoint.com/SiteAssets/CDBPromotedLinks
Replace tenantname with your tenancy name and see if that resolves. 

If it doesn't, you need to upload the folder to that location.

Hope that helps,
Tony

**Comment by mastj25** [comment]
Thank you Tony for your quick response!  You were right on point, I uploaded it to the site assets library on the site I was working on and not the root.  Sorry for that mistake.  I now have it added to the page.  Thanks for the solution and again for the quick response.

**Comment by CloudDesignBox** [comment]
Great! Remember that your users will need read access to that site assets library even if you're using the web part on another site. You could give the "Everyone except external users" read access so they don't get that error message.
