### ISSUE TITLE
Manage Lists

### ISSUE THREAD

**Issue by kieransaul** [CloudDesignBox/cdb-promoted-links#10]
Hi,

I'm trying to setup this up on our tenant to use this in SharePoint, when I click on the Manage List button on the Promoted Links it brings me to the site content window. 

In the developer tools we can see this:

![image](https://user-images.githubusercontent.com/9503635/51039854-15751c00-15ae-11e9-886e-27bb797eec1c.png)

Any help would be greatly appreciated 

Thanks!

**Comment by CloudDesignBox** [comment]
Hi kieransaul,

Initially it looks to see if the promoted links list exists, if it doesn't you can open the web part properties and select a promoted links list on the site.
If you haven't created a promoted links list yet, you will need to create a promoted links list under site contents. 
![image](https://user-images.githubusercontent.com/17725046/51041015-db594980-15b0-11e9-9059-23d2db59ff58.png)
![image](https://user-images.githubusercontent.com/17725046/51041046-eb712900-15b0-11e9-8d07-3e021d65632a.png)
You will then be able to select the list from the web part properties.

We do have a version of this to create a promoted links list directly from the web part, but i havent had chance to add this to our free web part yet.

**Comment by kieransaul** [comment]
Thanks, i've managed to sort this. It was a mixture of permissions issues and not having the list.

Thank you for help.
