### ISSUE TITLE
Correlation error on implementation

### ISSUE THREAD

**Issue by jorylubbers** [CloudDesignBox/cdb-promoted-links#12]
I am using the latest Sharepoint Online and am trying to add this App. implementing is however returning a error (translated): Implementation has failed. Correlation-ID: a7b8f19e-b022-1000-00d1-dc14bf06f249. 

I have added the folder "CDBPromotedLinks" to the site resources of my main "https://xxxxxxxxx.sharepoint.com/SiteAssets/Forms/AllItems.aspx" site and several other "https://xxxxxxxxx.sharepoint.com/sites/xxxxxxxx/SiteAssets/Forms/AllItems.aspx" to be sure.

I have rights to everything. 

The promoted links app is not available to me on the modern site.

Any idea what is going wrong here?

![2019-07-19 11_14_30-Apps voor SharePoint - Alle apps](https://user-images.githubusercontent.com/53079891/61524279-73c7ff00-aa16-11e9-8847-a15eeaae8167.png)

**Comment by CloudDesignBox** [comment]
Hi @jorylubbers 

This won't be an issue were you add the resource folder (that won't make it error in the app catalog).

Can you add other packages into the app catalog ok? Have you tried deleting it from the app catalog and uploading it again?

Thanks,
Tony
