### ISSUE TITLE
No Values in the List drop down

### ISSUE THREAD

**Issue by Steve344** [CloudDesignBox/cdb-promoted-links#2]
I've installed the webpart as per the instructions and added it to a page. I've created a list however when I edit the webpart the list dropdown box doesn't have any content, I'm assuming the problem is me, but what am I not doing/doing incorrectly

**Comment by CloudDesignBox** [comment]
Hi @Steve344 

The list needs to be created using the promoted links template.
In site contents, go to "New" --> "App"
Select the promoted links list (see below)
![promo](https://user-images.githubusercontent.com/17725046/39317857-88b7c796-4974-11e8-9a4f-a79d91b0b065.JPG)

Add the web part onto a page on the same site and you should have it appear in the drop down. You will need to add some promoted links to the list before you start seeing tiles.

Hope that helps,
Tony

**Comment by Steve344** [comment]
Tony, thanks for this, proof if proof was needed that it the problem is always in the chair and not in the computer, my problem solved.

Thanks again

Steve
