### ISSUE TITLE
Promoted Links not opening in new tab

### ISSUE THREAD

**Issue by JohanKleinHolte** [CloudDesignBox/cdb-promoted-links#3]
Hi all,

I definitely like the Promotedlinks web part you created, but I ran into a problem.
The underlying promoted links list in SharePoint has the possibility to specify if the URL needs to open as a dialog, or in the same window or in a new window.

The problem is that in the CloudDesignBox webpart the links will all open in the same window, no matter what the setting in the underlying SP list. 

I tested it in the Chrome browser, on a classic and a modern SP online page. Hope you can fix this. 
Thanks in advance!

**Comment by CloudDesignBox** [comment]
Hi Johan,

I've done some testing and I'm unable to replicate your issue. "New Tab" and "In page navigation" work as expected.
![promo1](https://user-images.githubusercontent.com/17725046/39983900-3a083758-5751-11e8-8902-7310ec205ab0.JPG)
![promo2](https://user-images.githubusercontent.com/17725046/39983935-52f46d54-5751-11e8-8593-95713e5ca08f.JPG)
Could you provide step by step guide on how you replicate this error? Can you also confirm that you are on the latest release 3.0.0.2?
Thanks,
Tony

**Comment by JohanKleinHolte** [comment]
Hi Tony,

Thank you very much for your answer.
The problem had to do with the language. In Dutch there was “Nieuwe tab” and not the English text “New tab”
That caused the issue!

I changed the texts in the Choice field and it worked!

Thanks a lot, and keep up the good work!

Johan Klein Holte
www.mensencloud.nl



Van: Tony Phillips [mailto:notifications@github.com]
Verzonden: Monday, May 14, 2018 09:35
Aan: CloudDesignBox/cdb-promoted-links <cdb-promoted-links@noreply.github.com>
CC: Johan Klein Holte <johan@mensencloud.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [CloudDesignBox/cdb-promoted-links] Promoted Links not opening in new tab (#3)


Hi Johan,

I've done some testing and I'm unable to replicate your issue. "New Tab" and "In page navigation" work as expected.
[promo1]<https://user-images.githubusercontent.com/17725046/39983900-3a083758-5751-11e8-8902-7310ec205ab0.JPG>
[promo2]<https://user-images.githubusercontent.com/17725046/39983935-52f46d54-5751-11e8-8593-95713e5ca08f.JPG>
Could you provide step by step guide on how you replicate this error? Can you also confirm that you are on the latest release 3.0.0.2?
Thanks,
Tony

**Comment by CloudDesignBox** [comment]
Great thank you for the update!

Tony

**Comment by SjoerdV** [comment]
Great work on the webpart. The 'Open as dialog box' option is not working (as in the originally question), so I thought I would comment on this issue.
![image](https://user-images.githubusercontent.com/13275320/52347139-87ac1580-2a21-11e9-9158-3cae05e0c9ba.png)

**Comment by CloudDesignBox** [comment]
We don't support open in Dialog in the new Modern experience. Does the link still open for you?

**Comment by SjoerdV** [comment]
Ah right. 
Yes it does open, like an 'In Page' link. Thanks for clearing that up.  
Although the modern (Tiles) list view it self does open up a dialog when the Launch behaviour Dialog is selected:
![image](https://user-images.githubusercontent.com/13275320/52361904-9f929200-2a3f-11e9-88cd-6bc66805c177.png)

**Comment by CloudDesignBox** [comment]
It would be great to write this again in react and make use of the dialog placeholder but we wont have resources to do this for a while. 
The initial idea was to get promoted links rendering on modern pages, thank you for all your suggestions, we will take them onboard.
