### ISSUE TITLE
web part not loading

### ISSUE THREAD

**Issue by mguendel** [CloudDesignBox/cdb-promoted-links#4]
I´ve been creating pages with this web part for a couple of weeks. At the beginning it worked great but now it's not loading. In every page I'm using  it it's stuck on " Loading Promoted Links... "

Any Idea?

![image](https://user-images.githubusercontent.com/14341525/42358735-67ca9618-809b-11e8-8318-5e5084e03a12.png)

If I Edit the page, it loads. I've tried removing the web part from the page and adding it again. I publish the page and then when I refresh the page it get stuck again.

Thank you in advance

**Comment by CloudDesignBox** [comment]
I'm unable to replicate this issue. In chrome, if you press F12 and reload the page, do you get any errors in the console log?

Thanks,
Tony

**Comment by mguendel** [comment]
Seems that the problem wasn't the web part. Since that day the webpart have been loading with no errors. Thank you anyway.
