### ISSUE TITLE
Images get cut in mobile devices

### ISSUE THREAD

**Issue by mguendel** [CloudDesignBox/cdb-promoted-links#5]
Hello
Have you considered to adjust the style to avoid images to get cut when browsing the page in a mobile device?

![image](https://user-images.githubusercontent.com/14341525/42850829-c90fd524-89e6-11e8-90a5-2f9a483c917e.png)

**Comment by CloudDesignBox** [comment]
Thank you for your feedback. There is an option to select a background image size in the web part properties. The "Cover" size option fills the background to the size of the tile and the title background is transparent so you can see all of the icon. There are smaller background sizes which do not go behind the title.
