### ISSUE TITLE
External user error

### ISSUE THREAD

**Issue by CloudDesignBox** [CloudDesignBox/cdb-promoted-links#7]
Hi All, we are having problems rendering correctly for external users.  The Tiles do not appear and external user get an error:

Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

TECHNICAL DETAILS

[SPLoaderError.loadComponentError]: ***Failed to load component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart). Original error: ***Failed to load path dependency "CloudDesignBoxPromotedLinksWebPartStrings" from component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart). Original error: Error loading https://component-id.invalid/5b0eac5a-50ba-4e01-8eb4-1767151d07f8_0.0.1/CloudDesignBoxPromotedLinksWebPartStrings Unable to load script /SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js ***INNERERROR: ***Failed to load path dependency "CloudDesignBoxPromotedLinksWebPartStrings" from component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart). Original error: Error loading https://component-id.invalid/5b0eac5a-50ba-4e01-8eb4-1767151d07f8_0.0.1/CloudDesignBoxPromotedLinksWebPartStrings Unable to load script /SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js ***CALLSTACK: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.020/sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:745:15996) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.020/sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605:21732) at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.020/sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605:15687) at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.020/sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605:11718) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.020/sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605:70129

 

Chrome Console issues an error Failed to load component:

 

sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:745 Uncaught (in promise) Error: ***Failed to load component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart).

Original error: ***Failed to load path dependency "CloudDesignBoxPromotedLinksWebPartStrings" from component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart).

Original error: Error loading https://component-id.invalid/5b0eac5a-50ba-4e01-8eb4-1767151d07f8_0.0.1/CloudDesignBoxPromotedLinksWebPartStrings

               Unable to load script /SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js

    at t [as constructor] (sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:745)

    at new t (sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605)

    at Function.e.buildErrorWithVerboseLog (sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605)

    at Function.e.buildLoadComponentError (sp-pages-assembly_en-us_6f3fffaf5b0c014e8435f05fdd316f89.js:1605)

 

Can you advise

**Comment by CloudDesignBox** [comment]
Hi Michael,

From your error message, it looks like the logged in user cannot access the SiteAssets library (where you uploaded the installation files). Users will need at least read access to this library for the web part to work. https://**tenant**.sharepoint.com/siteassets
*replace tenant with your tenant name.

Can you check that you have given the users access to this library?

Thanks,
Tony

**Comment by RM-GDA** [comment]
We have the same issue but we are hesitant to give external users access to the root site collection. We have a resources site that we give external users access, could the scripts be stored here and the path edited for the script’s to load from the subsite.

**Comment by CloudDesignBox** [comment]
Hi @RM-GDA , 

You can change the path in the write-manifests file:
https://github.com/CloudDesignBox/cdb-promoted-links/blob/master/config/write-manifests.json
You would then have to recompile the solution.

Hope that helps,
Tony
