### ISSUE TITLE
getting localhost error

### ISSUE THREAD

**Issue by Rajrup-net** [CloudDesignBox/cdb-promoted-links#9]
Hi All,
when I am trying to run the application in local bench I am getting this error:

**### **_This site can’t provide a secure connection localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR_****

can you please help me out... Its very urgent for me... Thanks in advance

**Comment by CloudDesignBox** [comment]
Hi @Rajrup-net ,
This will not run a local workbench as it uses real SharePoint data to do the REST calls. You can use the Microsoft hosted workbench page in a real tenancy where the list exists. 
Hope that helps,
Tony

**Comment by Rajrup-net** [comment]
@CloudDesignBox  Ok.. thanks.. But I am facing another issue. I am not able to select any view. I mean I am adding multiple items in list and I gave order no for those items and want to show in view.. Now all items are coming in view. I am not able to filter. Before in old sharepoint web-part edit properties view options was there.. Can you please help me out ??

**Comment by CloudDesignBox** [comment]
@Rajrup-net The ordering is applied to the web part. There is no option to select a view in the web part properties.
